#!/usr/bin/env node
/** Pure Node.js runtime guardian entrypoint for the packaged desktop application. */

import { randomUUID } from 'node:crypto'
import { spawn, type ChildProcess } from 'node:child_process'
import { isAbsolute } from 'node:path'
import { pathToFileURL } from 'node:url'
import {
  createNodeGuardianHostEndpoint,
  startGuardianHost,
  type GuardianHostIpcEndpoint,
  type GuardianOwnedSidecar,
} from '@deepseek-ai/dsh-subprocess-guardian/host'
import { MacOsProcessCapsuleTransport } from '@deepseek-ai/dsh-subprocess-guardian/macos-capsule'
import {
  MacOsCapsuleSupervisor,
  WindowsJobSupervisor,
  guardianChildEnv,
  type GuardianProcessSupervisor,
  type MacOsOwnershipMirror,
} from '@deepseek-ai/dsh-subprocess-guardian/supervisor'
import { createKoffiWindowsJobTransport } from '@deepseek-ai/dsh-subprocess-guardian/windows-koffi'
import {
  DESKTOP_GUARDIAN_CONTROL_NAMESPACE,
  DESKTOP_GUARDIAN_CONTROL_VERSION,
  isDesktopGuardianControlEnvelope,
  parseDesktopGuardianControlInboundFrame,
  type DesktopGuardianControlOutboundFrame,
} from './guardian-control.ts'
import { createDesktopJsonGuardianEndpoint } from './parent-ipc.ts'

/** Same-runtime guardian-to-sidecar child-process serialization mode. */
export const DESKTOP_SIDECAR_IPC_SERIALIZATION = 'advanced' as const

/** Validated app-owned arguments passed by Electron main to the bundled Node.js runtime. */
export interface DesktopGuardianArguments {
  readonly sidecarEntry: string
  readonly capsuleHelper?: string | undefined
  readonly maxBodyBytes: number
  readonly maxChunkBytes: number
  readonly maxInflightBytes: number
  readonly nativePollMs: number
  readonly gracefulShutdownMs: number
  readonly forceShutdownMs: number
  readonly mirrorTimeoutMs: number
  readonly mainLivenessFd?: number | undefined
}

/**
 * Parse the closed guardian command line generated by Electron main.
 * @param argv - arguments after the guardian entry path.
 * @param platform - target platform used to require its native inputs.
 * @returns validated absolute paths and positive integer bounds.
 */
export function parseDesktopGuardianArguments(
  argv: readonly string[],
  platform: NodeJS.Platform = process.platform,
): DesktopGuardianArguments {
  const values = new Map<string, string>()
  for (const argument of argv) {
    if (!argument.startsWith('--') || !argument.includes('=')) throw new Error('desktop guardian: malformed argument')
    const separator = argument.indexOf('=')
    const key = argument.slice(2, separator)
    const value = argument.slice(separator + 1)
    if (key.length === 0 || value.length === 0 || values.has(key)) {
      throw new Error('desktop guardian: duplicate or empty argument')
    }
    values.set(key, value)
  }
  const allowed = new Set([
    'sidecar-entry',
    'max-body-bytes',
    'max-chunk-bytes',
    'max-inflight-bytes',
    'native-poll-ms',
    'graceful-shutdown-ms',
    'force-shutdown-ms',
    'mirror-timeout-ms',
    ...(platform === 'darwin' ? ['capsule-helper', 'main-liveness-fd'] : []),
  ])
  if ([...values.keys()].some(key => !allowed.has(key))) throw new Error('desktop guardian: unknown argument')
  if (platform !== 'darwin' && platform !== 'win32') throw new Error(`desktop guardian: unsupported platform ${platform}`)
  const maxBodyBytes = integerArgument(values, 'max-body-bytes')
  const maxChunkBytes = integerArgument(values, 'max-chunk-bytes')
  const maxInflightBytes = integerArgument(values, 'max-inflight-bytes')
  if (maxChunkBytes > maxInflightBytes) throw new Error('desktop guardian: max chunk exceeds in-flight credit')
  return {
    sidecarEntry: absoluteArgument(values, 'sidecar-entry'),
    maxBodyBytes,
    maxChunkBytes,
    maxInflightBytes,
    nativePollMs: integerArgument(values, 'native-poll-ms'),
    gracefulShutdownMs: integerArgument(values, 'graceful-shutdown-ms'),
    forceShutdownMs: integerArgument(values, 'force-shutdown-ms'),
    mirrorTimeoutMs: integerArgument(values, 'mirror-timeout-ms'),
    ...(platform === 'darwin'
      ? {
        capsuleHelper: absoluteArgument(values, 'capsule-helper'),
        mainLivenessFd: inheritedDescriptorArgument(values, 'main-liveness-fd'),
      }
      : {}),
  }
}

class ElectronMainOwnershipMirror implements MacOsOwnershipMirror {
  private readonly pending = new Map<string, PromiseWithResolvers<string | undefined>>()

  constructor(
    private readonly parent: NodeJS.Process,
    private readonly timeoutMs: number,
  ) {}

  /** @inheritdoc */
  async register(
    capsuleId: string,
    pid: number,
    processGroupId: number,
    signal: AbortSignal,
  ): Promise<string> {
    const requestId = randomUUID()
    const response = this.addPending(requestId)
    await sendNode(this.parent, {
      namespace: DESKTOP_GUARDIAN_CONTROL_NAMESPACE,
      version: DESKTOP_GUARDIAN_CONTROL_VERSION,
      type: 'register',
      requestId,
      capsuleId,
      pid,
      processGroupId,
    })
    const receipt = await waitWithSignals(response, [signal, AbortSignal.timeout(this.timeoutMs)])
    if (typeof receipt !== 'string' || receipt.length === 0) {
      throw new Error('desktop guardian: main returned an invalid ownership receipt')
    }
    return receipt
  }

  /** @inheritdoc */
  async release(capsuleId: string): Promise<void> {
    const requestId = randomUUID()
    const response = this.addPending(requestId)
    await sendNode(this.parent, {
      namespace: DESKTOP_GUARDIAN_CONTROL_NAMESPACE,
      version: DESKTOP_GUARDIAN_CONTROL_VERSION,
      type: 'release',
      requestId,
      capsuleId,
    })
    await waitWithSignals(response, [AbortSignal.timeout(this.timeoutMs)])
  }

  /** @inheritdoc */
  async recover(capsuleId: string, reason: Error): Promise<void> {
    const requestId = randomUUID()
    const response = this.addPending(requestId)
    await sendNode(this.parent, {
      namespace: DESKTOP_GUARDIAN_CONTROL_NAMESPACE,
      version: DESKTOP_GUARDIAN_CONTROL_VERSION,
      type: 'recover',
      requestId,
      capsuleId,
      reason: reason.message.slice(0, 4096) || 'native capsule ownership was lost',
    })
    await waitWithSignals(response, [AbortSignal.timeout(this.timeoutMs)])
  }

  /**
   * Consume one main-to-guardian mirror response before the transparent sidecar relay.
   * @param value - untrusted parent IPC value.
   * @returns whether the mirror namespace owned the value.
   */
  consume(value: unknown): boolean {
    let frame
    try {
      frame = parseDesktopGuardianControlInboundFrame(value)
    } catch (error) {
      this.failAll(error instanceof Error ? error : new Error(String(error)))
      return true
    }
    if (frame === undefined) return false
    const pending = this.pending.get(frame.requestId)
    if (pending === undefined) return true
    this.pending.delete(frame.requestId)
    switch (frame.type) {
      case 'registered':
        pending.resolve(frame.receipt)
        break
      case 'released':
      case 'recovered':
        pending.resolve(undefined)
        break
      case 'failed':
        pending.reject(new Error(frame.message))
        break
    }
    return true
  }

  private addPending(requestId: string): Promise<string | undefined> {
    const deferred = Promise.withResolvers<string | undefined>()
    void deferred.promise.catch(() => undefined)
    this.pending.set(requestId, deferred)
    void deferred.promise.finally(() => { this.pending.delete(requestId) }).catch(() => undefined)
    return deferred.promise
  }

  private failAll(error: Error): void {
    for (const pending of this.pending.values()) pending.reject(error)
    this.pending.clear()
  }
}

class DirectNodeSidecarOwner implements GuardianOwnedSidecar {
  readonly pid: number
  readonly ipc: GuardianHostIpcEndpoint
  private readonly exited = Promise.withResolvers<void>()
  private shutdown: Promise<void> | undefined

  constructor(
    private readonly child: ChildProcess,
    private readonly gracefulShutdownMs: number,
    private readonly forceShutdownMs: number,
  ) {
    if (!Number.isSafeInteger(child.pid) || (child.pid as number) <= 0) {
      throw new Error('desktop guardian: sidecar did not publish a positive pid')
    }
    this.pid = child.pid as number
    this.ipc = createNodeGuardianHostEndpoint(child as unknown as Parameters<typeof createNodeGuardianHostEndpoint>[0])
    child.once('exit', () => { this.exited.resolve() })
    child.once('error', (error) => { this.exited.reject(error) })
    void this.exited.promise.catch(() => undefined)
  }

  /** @inheritdoc */
  terminateAndJoin(_reason: Error): Promise<void> {
    this.shutdown ??= this.stop()
    return this.shutdown
  }

  private async stop(): Promise<void> {
    if (this.child.exitCode !== null || this.child.signalCode !== null) return
    this.child.kill('SIGTERM')
    if (await settlesWithin(this.exited.promise, this.gracefulShutdownMs)) return
    this.child.kill('SIGKILL')
    if (!await settlesWithin(this.exited.promise, this.forceShutdownMs)) {
      throw new Error('desktop guardian: sidecar did not exit after forced termination')
    }
  }
}

async function createSupervisor(
  config: DesktopGuardianArguments,
  parent: NodeJS.Process,
): Promise<{
  readonly supervisor: GuardianProcessSupervisor
  readonly consumeParentControl?: ((value: unknown) => boolean) | undefined
}> {
  if (process.platform === 'win32') {
    const native = await createKoffiWindowsJobTransport({
      activeProcessPollMs: config.nativePollMs,
      pipeReadBytes: config.maxChunkBytes,
    })
    return { supervisor: new WindowsJobSupervisor(native) }
  }
  if (config.capsuleHelper === undefined || config.mainLivenessFd === undefined) {
    throw new Error('desktop guardian: macOS native inputs are missing')
  }
  const transport = new MacOsProcessCapsuleTransport({
    helperPath: config.capsuleHelper,
    mainLivenessFd: config.mainLivenessFd,
    maxSpecBytes: config.maxBodyBytes,
    groupPollMs: config.nativePollMs,
  })
  await transport.init()
  const mirror = new ElectronMainOwnershipMirror(parent, config.mirrorTimeoutMs)
  return {
    supervisor: new MacOsCapsuleSupervisor(transport, mirror),
    consumeParentControl: value => mirror.consume(value),
  }
}

/**
 * Run the packaged guardian entrypoint against its inherited process channels.
 * @returns after the sidecar and every managed process ownership unit are joined.
 */
export async function runDesktopGuardian(): Promise<void> {
  if (typeof process.send !== 'function' || !process.connected) {
    throw new Error('desktop guardian: a connected JSON parent IPC channel is required')
  }
  const config = parseDesktopGuardianArguments(process.argv.slice(2))
  const { supervisor, consumeParentControl } = await createSupervisor(config, process)
  const sidecarChild = spawn(process.execPath, [config.sidecarEntry], {
    stdio: ['ignore', 'inherit', 'inherit', 'ipc'],
    serialization: DESKTOP_SIDECAR_IPC_SERIALIZATION,
    shell: false,
    windowsHide: true,
    env: guardianChildEnv(),
  })
  const sidecar = new DirectNodeSidecarOwner(
    sidecarChild,
    config.gracefulShutdownMs,
    config.forceShutdownMs,
  )
  const sidecarStarted: DesktopGuardianControlOutboundFrame = {
    namespace: DESKTOP_GUARDIAN_CONTROL_NAMESPACE,
    version: DESKTOP_GUARDIAN_CONTROL_VERSION,
    type: 'sidecar-started',
    sidecarPid: sidecar.pid,
  }
  const announced = sendNode(process, sidecarStarted)
  const host = startGuardianHost({
    parent: createDesktopJsonGuardianEndpoint(
      process as unknown as Parameters<typeof createDesktopJsonGuardianEndpoint>[0],
      config.maxChunkBytes,
    ),
    sidecar,
    supervisor,
    limits: {
      maxBodyBytes: config.maxBodyBytes,
      maxChunkBytes: config.maxChunkBytes,
      maxInflightBytes: config.maxInflightBytes,
    },
    isSidecarReservedMessage: isDesktopGuardianControlEnvelope,
    ...(consumeParentControl === undefined ? {} : { isParentControlMessage: consumeParentControl }),
  })
  try {
    await announced
  } catch (error) {
    await host.dispose(error instanceof Error ? error : new Error(String(error)))
    throw error
  }
  process.once('SIGTERM', () => { void host.dispose(new Error('desktop guardian: SIGTERM')) })
  process.once('SIGINT', () => { void host.dispose(new Error('desktop guardian: SIGINT')) })
  await host.done
  await sendNode(process, {
    namespace: DESKTOP_GUARDIAN_CONTROL_NAMESPACE,
    version: DESKTOP_GUARDIAN_CONTROL_VERSION,
    type: 'sidecar-joined',
    sidecarPid: sidecar.pid,
  } satisfies DesktopGuardianControlOutboundFrame)
  disconnectParentIfConnected(process)
}

function integerArgument(values: ReadonlyMap<string, string>, name: string): number {
  const source = values.get(name)
  if (source === undefined || !/^[1-9][0-9]*$/u.test(source)) throw new Error(`desktop guardian: ${name} is required`)
  const value = Number(source)
  if (!Number.isSafeInteger(value)) throw new Error(`desktop guardian: ${name} exceeds the safe integer range`)
  return value
}

function absoluteArgument(values: ReadonlyMap<string, string>, name: string): string {
  const value = values.get(name)
  if (value === undefined || !isAbsolute(value)) throw new Error(`desktop guardian: ${name} must be absolute`)
  return value
}

function inheritedDescriptorArgument(values: ReadonlyMap<string, string>, name: string): number {
  const value = integerArgument(values, name)
  if (value < 3) throw new Error(`desktop guardian: ${name} must name an inherited descriptor`)
  return value
}

function sendNode(target: NodeJS.Process, value: unknown): Promise<void> {
  return new Promise((resolve, reject) => {
    if (typeof target.send !== 'function' || !target.connected) {
      reject(new Error('desktop guardian: Electron main IPC disconnected'))
      return
    }
    target.send(value, (error) => {
      if (error === null) resolve()
      else reject(error)
    })
  })
}

function disconnectParentIfConnected(target: NodeJS.Process): void {
  if (target.connected) target.disconnect()
}

async function waitWithSignals<T>(promise: Promise<T>, signals: readonly AbortSignal[]): Promise<T> {
  const signal = AbortSignal.any([...signals])
  signal.throwIfAborted()
  return new Promise((resolve, reject) => {
    const aborted = (): void => { reject(asError(signal.reason, 'desktop guardian: operation aborted')) }
    signal.addEventListener('abort', aborted, { once: true })
    void promise.then(
      (value) => { signal.removeEventListener('abort', aborted); resolve(value) },
      (error: unknown) => {
        signal.removeEventListener('abort', aborted)
        reject(asError(error, 'desktop guardian: operation failed'))
      },
    )
  })
}

function asError(value: unknown, fallback: string): Error {
  return value instanceof Error ? value : new Error(fallback, { cause: value })
}

async function settlesWithin(promise: Promise<void>, milliseconds: number): Promise<boolean> {
  let timer: NodeJS.Timeout | undefined
  const timedOut = new Promise<false>((resolve) => {
    timer = setTimeout(() => { resolve(false) }, milliseconds)
    timer.unref()
  })
  const result = await Promise.race([promise.then(() => true), timedOut])
  if (timer !== undefined) clearTimeout(timer)
  return result
}

const invokedPath = process.argv[1]
if (invokedPath !== undefined && import.meta.url === pathToFileURL(invokedPath).href) {
  try {
    await runDesktopGuardian()
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    if (typeof process.send === 'function' && process.connected) {
      await sendNode(process, { version: 1, type: 'desktop-runtime-failed', message }).catch(() => undefined)
    }
    process.stderr.write(`desktop guardian: ${message}\n`)
    process.exitCode = 1
  }
}
